"$schema" = "./node_modules/wrangler/config-schema.json"
name = 'hugentobler-website'
compatibility_date = '2026-03-05'
compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = '.svelte-kit/cloudflare'

[[d1_databases]]
binding = "DB"
database_name = "hugentobler-website-visits"
database_id = "c3bc36a4-72ad-4430-b2df-094a078e8a83"